### ISSUE TITLE
Can't set default language

### ISSUE THREAD

**Issue by Befrog57** [leihs/leihs-instance#11]
Hi,

how do I set the default Language? It seems that the permissions appear to be bugged. When I try changing the language settings via the admin pannel it says that I " [...] don't have appropriate permission to perform this operation".
In addition the site seems to be a mixture of English and German words, witch will be worrying for most users, do you have a fix for that?

Kind regards
-befrog

**Comment by eins78** [comment]
Leihs version 6.0.0 has been released: https://github.com/leihs/leihs-instance/blob/943994496d0017a5dea03026dff08efa0b3e3350/GUIDE.md

You can now configure the languages in the new admin UI: https://leihs.example.org/admin/settings/languages/

Please report any missing translation parts in the main apps (borrow, lending and manage) to the main leihs repo: https://github.com/leihs/leihs/issues/new
