### ISSUE TITLE
Fehler beim Ausführen von ./scripts/deploy-from-docker

### ISSUE THREAD

**Issue by xyllyxy** [leihs/leihs-instance#12]
Hello, 
i have a problem with one script here: when i'm at the installation step:

./scripts/deploy-from-docker

i am getting:
[...]
`Step 22/22 : WORKDIR /leihs/deploy
 ---> Using cache
 ---> 23121723ade7
Successfully built 23121723ade7
Successfully tagged leihs/ansible-controller:latest

PLAY [all] ********************************************************************************************************************************************************************************************************************************************************************

TASK [install system python] **************************************************************************************************************************************************************************************************************************************************
fatal: [servername]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: Warning: Permanently added 'servername,ip' (ECDSA) to the list of known hosts.
root@servername: Permission denied (publickey,password).
`
If i test it with ssh root@servername i get in (with publickey, not with password - for test i deactivated the passphrase too, but nevertheless i get this message...

With ./scripts/deploy-from-docker -vvv i get an actually clear failure: 

debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug3: no such identity: /root/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /root/.ssh/id_xmss
debug3: no such identity: /root/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
root@servername: Permission denied (publickey,password).

I tried to uncommand 
 `  IdentityFile ~/.ssh/id_rsa
   PermitRootLogin yes`
in the /etc/ssh/ssh_conf
and 
`PasswordAuthentication yes
PermitRootLogin yes
RSAAuthentication yes
PubkeyAuthentication yes`
in the  /etc/ssh/sshd_conf
and 
i set all right als /root/.ssh/* correct (private keys only owner, pubkey readable for all, etc...) but still the failure appears... 
I don't get why the script actually have to ssh to its own...

ssh "${LEIHS_HOST_USER}@${LEIHS_HOSTNAME}" -- 'test $(id -u) -eq 0 && echo OK || sudo echo OK'

gives me from the beginning an "OK"

Have anyone an idea?

Thanks
xyllyxy

**Comment by eins78** [comment]
You'll need to adapt the "docker wrapper" script to your situation regarding SSH authentication. 
https://github.com/leihs/leihs-instance/blob/2355863d7a1a9572aca5d33978d216dda4f43713/scripts/-from-docker#L20
The default setting work out of the box if you have `ssh-agent` set up. 
Another option would be "pass through" ssh keys with mounts, the simplest way would be to mirror your local directory: `-v "$(HOME).ssh/:/root/ssh/"`.

**Comment by xyllyxy** [comment]
Thank you - that helped
