### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by lbarning** [leihs/leihs-instance#13]
Whenever I try to deploy leihs from my controll mashine with docker I get an ssh error:
Failed to connect to the host via ssh:
```
Warning: Permanently added 'host,ip' (ECDSA) to the list of known hosts.
root@host: Permission denied (publickey).

PLAY RECAP *******************************************************************************************************************
host : ok=0    changed=0    unreachable=1    failed=0   
```
Outside of the deploymet process the ssh connection is working fine and ssh-agent-forwarding is also enabled.

I also tried the dockerless deployment but sadly that doesn't seem to work ether.
It gives me the following output but after that nothing happends and I get droped back into my shell

```
+ git submodule update --recursive --init --force --quiet
+ cd leihs/deploy
+ bin/ansible-playbook -i ../../hosts -e use_s3_build_cache=yes deploy_play.yml
✪ virtualenv: preparing…
```

My host is on debian 10 (buster) and my contoll mashine on debian testing (bullseye)

**Comment by satshas** [comment]
Hello,

I have the same issue deploying with Docker, while trying to connect with a different user than root (but still having root privileges).

```
fatal: [XXX.XXX.XXX.XXX]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: Warning: Permanently added 'XXX.XXX.XXX.XXX' (ECDSA) to the list of known hosts.
daniele@XXX.XXX.XXX.XXX: Permission denied (publickey,password).



PLAY RECAP ****************************************************************************
XXX.XXX.XXX.XXX            : ok=0    changed=0    unreachable=1    failed=0 
```

Same as above, outside deployment the SSH is working fine, and did work fine during the deployment guide.
I also tried to change options of the ansible.cfg inside the leihs instance but I saw it gets rewritten while running the deploy.

Do you know a quick solution to the problem?

Control machine: Ubuntu 20.04 
Host: Ubuntu Server 16.04

Daniele

**Comment by lbarning** [comment]
We needed to add the local ssh-files to the scripts/-from-docker file.

```-v "/home/$USER/.ssh/:/root/.ssh/" \```

Our files looks like this:

```
#!/bin/sh -eu

# build the docker image and tag it with a name
docker build -t leihs/ansible-controller ./leihs/deploy

# start a temporary container from this image,
# mounting our working directory in it,
# passing through ssh-agent from host so passwordless auth works,
# then run given command
docker run --rm -it \
    -w "/leihs-instance/leihs/deploy" \
    -v "$(pwd):/leihs-instance" \
    -v "$(pwd)/tmp:/tmp/tmp" \
    -v "$(pwd)/leihs:/leihs" \
    -e S3_CACHE_ENDPOINT="${S3_CACHE_ENDPOINT:-}" \
    -e S3_CACHE_BUCKET="${S3_CACHE_BUCKET:-}" \
    -e S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID:-}" \
    -e S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY:-}" \
    -v "/home/$USER/.ssh/:/root/.ssh/" \
    leihs/ansible-controller \
    "$@"
```

After that we got an error regarding the .ssh/config file which was moved to config.old as a quick fix.
I hope this is helpful.

Lukas
