### ISSUE TITLE
Deployment not working (mimemagic (0.3.0) - version could not be found)

### ISSUE THREAD

**Issue by MatKDA** [leihs/leihs-instance#14]
Hi,
I've got a problem installing leihs.
Following the "leihs Hosting Guide", I get the following error (`./scripts/deploy-from-docker`):
```
TASK [leihs-legacy-install : install bundler and bundle] ***********************
fatal: [....de]: FAILED! => {
    "changed": true, 
    "cmd": "set -eux\n export PATH=$HOME/.rubies/ruby-2.6.6/bin:$PATH\n which gem\n gem install bundler\n cd /leihs/legacy\n bundle install --retry=12 --without development --without test", 
    "delta": "0:00:24.507679", 
    "end": "2021-03-25 13:41:12.534025", 
    "rc": 7, 
    "start": "2021-03-25 13:40:48.026346"
}

STDOUT:

/home/leihs-legacy/.rubies/ruby-2.6.6/bin/gem
Successfully installed bundler-2.2.15
Parsing documentation for bundler-2.2.15
Done installing documentation for bundler after 2 seconds
1 gem installed
Resolving dependencies...
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/.......
Your bundle is locked to mimemagic (0.3.0), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.0) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.0) that hasn't been removed
in order to install.


STDERR:

+ export PATH=/home/leihs-legacy/.rubies/ruby-2.6.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ which gem
+ gem install bundler
+ cd /leihs/legacy
+ bundle install --retry=12 --without development --without test


MSG:

non-zero return code

```
Control and target machines are both running fresh installations of ubuntu 18.04 or debian 10.

Thanks in advance,
Matthias

**Comment by eins78** [comment]
Sorry, but this problem ist outside of our control (for this version of Leihs). It will be fixed in the next stable version (v6, no ETA yet). See https://github.com/mimemagicrb/mimemagic/issues/98

If you're just trying out leihs, there should be a fix in the nightly version by tomorrow, so you could try that. If so, upgrade the leihs version first with `./scripts/update_leihs_latest master`.

**Comment by eins78** [comment]
A possible workaround that I am not recommending: replace the referenced version of `mimemagic` in every `Gemfile.lock`, from `0.3.0` to `0.3.6`.

**Comment by MatKDA** [comment]
Thanks for your replay.
I've replaced the referenced version of `mimemagic` from `0.3.0` to `0.3.7`. However, this led to new problems:
```
TASK [leihs-legacy-install : install bundler and bundle] ***********************
fatal: [...de]: FAILED! => {
    "changed": true, 
    "cmd": "set -eux\n export PATH=$HOME/.rubies/ruby-2.6.6/bin:$PATH\n which gem\n gem install bundler\n cd /leihs/legacy\n bundle install --retry=12 --without development --without test", 
    "delta": "0:01:18.787083", 
    "end": "2021-03-25 16:05:18.716395", 
    "rc": 34, 
    "start": "2021-03-25 16:03:59.929312"
}

STDOUT:

/home/leihs-legacy/.rubies/ruby-2.6.6/bin/gem
Successfully installed bundler-2.2.15
Parsing documentation for bundler-2.2.15
Done installing documentation for bundler after 2 seconds
1 gem installed
Resolving dependencies...
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rails-assets.org/...
Fetching rake 12.3.0
Installing rake 12.3.0
Fetching abstract_type 0.0.7
Installing abstract_type 0.0.7
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 0.8.6
Installing i18n 0.8.6
Using minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching activesupport 5.0.5
Installing activesupport 5.0.5
Fetching builder 3.2.3
Installing builder 3.2.3
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.2
Installing nokogiri 1.8.2 with native extensions
Fetching rails-dom-testing 2.0.3
Installing rails-dom-testing 2.0.3
Fetching crass 1.0.3
Installing crass 1.0.3
Fetching loofah 2.2.0
Installing loofah 2.2.0
Fetching rails-html-sanitizer 1.0.3
Installing rails-html-sanitizer 1.0.3
Fetching actionview 5.0.5
Installing actionview 5.0.5
Fetching rack 2.0.4
Installing rack 2.0.4
Fetching rack-test 0.6.3
Installing rack-test 0.6.3
Fetching actionpack 5.0.5
Installing actionpack 5.0.5
Fetching nio4r 2.1.0
Installing nio4r 2.1.0 with native extensions
Fetching websocket-extensions 0.1.2
Installing websocket-extensions 0.1.2
Fetching websocket-driver 0.6.5
Installing websocket-driver 0.6.5 with native extensions
Fetching actioncable 5.0.5
Installing actioncable 5.0.5
Fetching globalid 0.4.0
Installing globalid 0.4.0
Fetching activejob 5.0.5
Installing activejob 5.0.5
Fetching mime-types-data 3.2016.0521
Installing mime-types-data 3.2016.0521
Fetching mime-types 3.1
Installing mime-types 3.1
Fetching mail 2.6.6
Installing mail 2.6.6
Fetching actionmailer 5.0.5
Installing actionmailer 5.0.5
Fetching activemodel 5.0.5
Installing activemodel 5.0.5
Fetching arel 7.1.4
Installing arel 7.1.4
Fetching activerecord 5.0.5
Installing activerecord 5.0.5
Fetching ice_nine 0.11.2
Installing ice_nine 0.11.2
Fetching memoizable 0.4.2
Installing memoizable 0.4.2
Fetching adamantium 0.2.0
Installing adamantium 0.2.0
Fetching public_suffix 2.0.5
Installing public_suffix 2.0.5
Fetching addressable 2.5.1
Installing addressable 2.5.1
Fetching arrayfields 4.9.2
Installing arrayfields 4.9.2
Fetching ast 2.3.0
Installing ast 2.3.0
Using audited 4.5.0 from https://github.com/leihs/audited (at master@342b6b1)
Fetching htmlentities 4.3.4
Installing htmlentities 4.3.4
Fetching mimemagic 0.3.7
Downloading mimemagic-0.3.7 revealed dependencies not in the API or the lockfile
(nokogiri (~> 1.11.2)).
Either installing with `--full-index` or running `bundle update mimemagic`
should fix the problem.


STDERR:

+ export PATH=/home/leihs-legacy/.rubies/ruby-2.6.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ which gem
+ gem install bundler
+ cd /leihs/legacy
+ bundle install --retry=12 --without development --without test
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/axlsx-c8ac844572b2/axlsx.gemspec:12.


MSG:

non-zero return code
```

Is there an easy way to update the dependencies or do I have to manually fiddle with the `Gemfile.lock`s?

Again, thanks,
Matthias

**Comment by MatKDA** [comment]
Hi,
just another quick update: Version `0.3.6` also got yanked, so I guess we'd need `0.3.7`.
Thanks for your kind help,
Matthias

**Comment by eins78** [comment]
Thanks for the note about `0.3.7`, that saved me some time. To answer the first question: because a dependency was added to _this_ version, the Gemfile needs to reflect that as well (that is what the error message tries to say).

Anyways, it is fixed in the lastest "dev" version:
https://github.com/leihs/leihs/commit/2cb3f4e1ef9272ff63ceae4379aa749e28a4f9dc

I am planning to also release a versions `5.3.1` and some `6.0.0-RC.X` with the same fix, but as mentioned I recommend just using `master` branch if your only experimenting with Leihs.

**Comment by MatKDA** [comment]
Hello again,

thanks for your kind help.

I've encountered a new problem, however, as I'm not sure if this is really a problem or if I'm just unable to properly switch branches, I chose to not open a new issue - please bear with me.


I followed the guide ( https://github.com/leihs/leihs-instance/blob/master/GUIDE.md ), and after `sh -c 'git submodule update --init leihs && cd leihs && git submodule update --init --recursive'` I've changed branches:
`cd leihs; git checkout master --recurse-submodules; cd ..` - is this the correct way to do it? After issuing that command I'm on the "master" branch in all the submodules (leihs/legacy etc.). I've also noted, that before changing the branch to master, I was on `Release: 5.2.3` (`Vorherige Position von HEAD war 675f449a7 Release: 5.2.3`) -- is this intended?


As already mentioned, when I change the branch as described, I encounter a new problem: `TASK [leihs-my-install : create jar]` terminates with `/leihs-instance/leihs/deploy/../my/bin/build: line 37: lein: command not found`
(longer output here: https://pastebin.com/sXHPF2R2 )


Any ideas?


Thanks in advance,
Matthias

**Comment by eins78** [comment]
> is this the correct way to do it?

Yes, but then you need to either commit all submodules you've edited (in your case, in the inventory `git add leihs && git commit …`. Or, you can comment out this line: https://github.com/leihs/leihs-instance/blob/master/scripts/deploy#L3
Its there by default to make sure that only the commited version is deployed to production systems, but if your experimenting its easier without it.

Also, I am still working on a version 5.3.1 that might be ready soon. It will include some of the deploy-related fixes as well, and a simple way to use "prebuilt artefacts" so you dont have to build locally (otherwise you need quite an extensive development environment, this is where the `lein` error comes from).

**Comment by eins78** [comment]
@MatKDA please try again with version 5.3.1 https://github.com/leihs/leihs-instance/commit/aba8d088d46dfcf0e0b20bc12356a7b37498cff9

make sure that `-e 'use_s3_build_cache=yes'` is set, like in the default script https://github.com/leihs/leihs-instance/blob/aba8d088d46dfcf0e0b20bc12356a7b37498cff9/scripts/deploy#L8

then you dont need to compile anything, but you need either the `aws` cli installed (`brew install awscli`, `apt install awscli`, etc.) or use the docker version which already includes it.

**Comment by MatKDA** [comment]
Hello,

again, thanks for your quick help - much appreciated.

It's working now, at least the installer finishes without an error. But when I open the address, I get a "503 - Service Unavailable". However, at the moment I think the error is on my side (misconfiguration) - I'd open a new issue, if I can't resolve the problem...

Regards,
Matthias
