### ISSUE TITLE
Leihs version 6.0.0: TASK [leihs-mail-install : create jar] error

### ISSUE THREAD

**Issue by Befrog57** [leihs/leihs-instance#17]
Hi there it's me again :)

There seems to be a problem with the task "TASK [leihs-mail-install : create jar]" here is a snippet of the error message:
```
TASK [leihs-mail-install : create jar] ************************************************************
fatal: [host]: FAILED! => {
    "changed": true,
    "cmd": "DEPLOY_DIR='/home/user/xxx_hosting/leihs/deploy'\nPROJECT_DIR=\"${DEPLOY_DIR}/../mail\"\n${PROJECT_DIR}/bin/build\n",
    "delta": "0:00:01.728208",
    "end": "2021-05-26 09:07:55.872213",
    "rc": 1,
    "start": "2021-05-26 09:07:54.144005"
}

STDOUT:

PWD: /home/user/xxx_hosting/leihs/mail
BUILD_CACHE_DISABLED=NO
INFO: checking clean working_tree in /home/user/xxx_hosting/leihs/mail 
LOCAL_CACHED_ARTEFACT_PATH: /home/user/xxx_hosting/tmp/build_cache/leihs-mail_83db748459816530c20763e93d5391d9261bf3ee.jar
INFO: locally cached artefact found, extracting, and caching ...


STDERR:

+ PROJECT_NAME=leihs-mail
+++ dirname /home/user/xxx_hosting/leihs/deploy/../mail/bin/build
++ cd -- /home/user/xxx_hosting/leihs/deploy/../mail/bin
++ cd ..
++ pwd -P
+ PROJECT_DIR=/home/user/xxx_hosting/leihs/mail
+ ARTEFACT_PATH=/home/user/xxx_hosting/leihs/mail/target/leihs-mail.jar
++ git -C /home/user/xxx_hosting/leihs/mail log -n 1 HEAD --pretty=%T
+ DIGEST=83db748459816530c20763e93d5391d9261bf3ee
+ LOCAL_CACHE_DIR=/home/user/xxx_hosting/tmp/build_cache
+ LOCAL_CACHED_ARTEFACT_PATH=/home/user/xxx_hosting/tmp/build_cache/leihs-mail_83db748459816530c20763e93d5391d9261bf3ee.jar
+ S3_CACHED_ARTEFACT_NAME=leihs-mail_83db748459816530c20763e93d5391d9261bf3ee.jar
+ BUILD_CACHE_DISABLED=NO
+ set +x
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- bundler/inline (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ./bin/s3-cache-helper:3:in `<main>'


MSG:

non-zero return code
```

At first I thought it might be something with a missing installation of Ruby 3.0.0 on my server, but that does not seem to be the problem. Then i installed bundler via gem, but this didn't help either. The server is running Ubuntu 20.04.2 LTS.

Kind regards
-befrog

**Comment by eins78** [comment]
so there are several things going on:

* the error is about the `bundler` gem missing on you control machine. if you do `gem install bundler` locally it should work for you. this escaped my testing because i use the deploy Docker container to catch any missing dependencies (that are always present on my machine), but it seems ruby-docker already includes the bundler.

* the specific script that is called is not supposed to run at all at this point, or should not stop on a failure. this needs a bugfix that will take some more time.

**Comment by Befrog57** [comment]
Hmm... this does not seem to be working... I did everything as advised.
Here is some more info of control machine:
```
$ bundle -v
Bundler version 2.2.18

$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.15
  - RUBY VERSION: 3.0.1 (2021-04-05 patchlevel 64) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/user/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/user/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/3.0.0
     - /home/user/.local/share/gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/user/.local/share/gem/ruby/3.0.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /opt/android-sdk/emulator
     - /usr/lib/jvm/default/bin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl

```

**Comment by eins78** [comment]
The only thing that comes to mind is you're using ruby 3.0.0 while we're on 2.6.6.
I dont think it's worth to debug this further, because the scripts need to be fixed anyhow.

If you want to keep debugging,  the minimal repro that should work is this:

```sh
ruby -e 'require "bundler/inline"; gemfile {ruby ">= 2.6";gem "activesupport","~> 6.0";}; puts :OK'
```

In case that works on your machine, but still not via the ansible scripts I would be kind of intrigued as to why… 

If you want to edit the scripts locally to get it working: remove all the lines with `./bin/s3-cache-helper upload` from all the `…/bin/build` shell scripts.

**Comment by Befrog57** [comment]
Thanks for all the work you put in for this. I've changed the `s3-cache-helper` file as described. Now its working.
As you predicted, it did crash again at `TASK [leihs-my-install : create jar]` with the same error that occurred to me at the beginning.

**Comment by eins78** [comment]
@Befrog57 please try the lastest version from Leihs `master` branch https://github.com/leihs/leihs/commit/53c5fe97a6c7e85e21178746399d5a432576dee4
the deploy should now run through.

**Comment by eins78** [comment]
@Befrog57 disregard my last comment – deploying some non-release version only works with a complete developer setup.
But, meanwhile there was an RC released which you can try: https://github.com/leihs/leihs/releases/tag/6.1.0-RC.1

**Comment by eins78** [comment]
@Befrog57 that sounds like you tried the new artefacts with the old version, but that wont work (because the artefacts are only used if they "match").
I try to be more clear: you should update `./leihs` to the RC.1 and then the artefact file will be downloaded and used automatically:

```sh
cd leihs
git fetch -q && git checkout 6.1.0-RC.1
cd ..
git add leihs && git commit -m 'leihs: 6.1.0-RC.1'
# run deploy
```

**Comment by Befrog57** [comment]
I have done that now... but it again stopping at the same task, maybe the error message will help you debugging.
```
TASK [leihs-my-install : create jar] *********************************
fatal: [URL]: FAILED! => {
    "changed": true,
    "cmd": "DEPLOY_DIR='/home/user/URL_hosting/leihs/deploy'\nPROJECT_DIR=\"${DEPLOY_DIR}/../my\"\n${PROJECT_DIR}/bin/build\n",
    "delta": "0:00:00.192090",
    "end": "2021-06-02 12:24:28.108431",
    "rc": 1,
    "start": "2021-06-02 12:24:27.916341"
}

STDOUT:

PWD: /home/user/URL_hosting/leihs/my
BUILD_CACHE_DISABLED=NO
INFO: checking clean working_tree in /home/user/URL_hosting/leihs/my 
LOCAL_CACHED_ARTEFACT_PATH: /home/user/URL_hosting/tmp/build_cache/leihs-my_884919fcaf70d137f6bd46659033e9792e2d758e.jar
INFO: locally cached artefact found, extracting, and caching ...


STDERR:

+ PROJECT_NAME=leihs-my
+++ dirname /home/user/URL_hosting/leihs/deploy/../my/bin/build
++ cd -- /home/user/URL_hosting/leihs/deploy/../my/bin
++ cd ..
++ pwd -P
+ PROJECT_DIR=/home/user/URL_hosting/leihs/my
+ UI_DIR=/home/user/URL_hosting/leihs/my/leihs-ui
+ ARTEFACT_PATH=/home/user/URL_hosting/leihs/my/target/leihs-my.jar
++ git -C /home/user/URL_hosting/leihs/my log -n 1 HEAD --pretty=%T
+ DIGEST=884919fcaf70d137f6bd46659033e9792e2d758e
+ LOCAL_CACHE_DIR=/home/user/URL_hosting/tmp/build_cache
+ LOCAL_CACHED_ARTEFACT_PATH=/home/user/URL_hosting/tmp/build_cache/leihs-my_884919fcaf70d137f6bd46659033e9792e2d758e.jar
+ S3_CACHED_ARTEFACT_NAME=leihs-my_884919fcaf70d137f6bd46659033e9792e2d758e.jar
+ BUILD_CACHE_DISABLED=NO
+ set +x
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- bundler/inline (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/user/URL_hosting/leihs/my/leihs-ui/bin/s3-cache-helper:3:in `<main>'


MSG:

non-zero return code
```

**Comment by eins78** [comment]
@Befrog57 I think it did not work as i expected because a `git submodule update --init --recursive --force` step was missing.
Anyways, in the meantime Leihs 6.1.0 was released including a fix for this problem, so you can use the regular upgrade as documented (https://github.com/leihs/leihs-instance/blob/master/GUIDE.md#upgrade), e.g. run `./scripts/update_leihs_latest stable` (which includes the submodule update).

**Comment by eins78** [comment]
fixed in https://github.com/leihs/leihs-instance/commit/8cc14af5a268032e6bc5a9626eebf1e5d5723d2f

upgrade instructions for existing inventory repos: https://github.com/leihs/leihs-instance/blob/mfa/master/GUIDE.md#upgrade
