### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by satshas** [leihs/leihs-instance#18]
Hello,

I have been trying to deploy leihs again on a new server with the following:

- control machine Ubuntu Desktop 20.04
- host machine: Ubuntu Server 18.04
- leihs updated to the last master version

This time the error is about npm, which is not found by one the of scripts (leihs/my/leihs-ui/bin/deps-install).
Making a script manually and running it into the server, finds npm without problems. 

Thanks for the help.

Below the log:

`TASK [leihs-my-install : create jar] ********************************************************************************************************************************************
fatal: [leihs.hochschule-rhein-waal.de]: FAILED! => {
    "changed": true,
    "cmd": "DEPLOY_DIR='/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/deploy'\nPROJECT_DIR=\"${DEPLOY_DIR}/../my\"\n${PROJECT_DIR}/bin/build\n",
    "delta": "0:00:01.646762",
    "end": "2021-06-14 19:56:17.554710",
    "rc": 1,
    "start": "2021-06-14 19:56:15.907948"
}

STDOUT:

PWD: /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my
BUILD_CACHE_DISABLED=NO
INFO: checking clean working_tree in /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my 
LOCAL_CACHED_ARTEFACT_PATH: /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/tmp/build_cache/leihs-my_fecf8df196351c3c0256b4bf67a4cb216cba3a12.jar
S3_CACHED_ARTEFACT_NAME: leihs-my_fecf8df196351c3c0256b4bf67a4cb216cba3a12.jar
INFO: trying to download from S3 cache
WARN: S3 env vars are not defined; exiting immediatelly without error
INFO: no cached artefact found: building, packing, and caching ...
PWD: /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my/leihs-ui
BUILD_CACHE_DISABLED=NO
INFO: checking clean working_tree in /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my/leihs-ui 
LOCAL_CACHED_ARTEFACT_PATH: /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/tmp/build_cache/leihs-ui_dd451b13830662189a1c066a546336a4f775ac72.tgz
S3_CACHED_ARTEFACT_NAME: leihs-ui_dd451b13830662189a1c066a546336a4f775ac72.tgz
INFO: trying to download from S3 cache
WARN: S3 env vars are not defined; exiting immediatelly without error
INFO: no cached artefact found: building, packing, and caching ...
build error!

STDERR:

+ PROJECT_NAME=leihs-my
+++ dirname /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/deploy/../my/bin/build
++ cd -- /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/deploy/../my/bin
++ cd ..
++ pwd -P
+ PROJECT_DIR=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my
+ UI_DIR=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my/leihs-ui
+ ARTEFACT_PATH=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my/target/leihs-my.jar
++ git -C /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my log -n 1 HEAD --pretty=%T
+ DIGEST=fecf8df196351c3c0256b4bf67a4cb216cba3a12
+ LOCAL_CACHE_DIR=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/tmp/build_cache
+ LOCAL_CACHED_ARTEFACT_PATH=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/tmp/build_cache/leihs-my_fecf8df196351c3c0256b4bf67a4cb216cba3a12.jar
+ S3_CACHED_ARTEFACT_NAME=leihs-my_fecf8df196351c3c0256b4bf67a4cb216cba3a12.jar
+ BUILD_CACHE_DISABLED=NO
+ set +x
+ PROJECT_NAME=leihs-ui
+++ dirname ./leihs-ui/bin/build
++ cd -- ./leihs-ui/bin
++ cd ..
++ pwd -P
+ PROJECT_DIR=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my/leihs-ui
+ ARTEFACT_NAME=leihs-ui
+ ARTEFACT_PATHS='./dist ./bootstrap-theme-leihs/build'
++ git -C /home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/leihs/my/leihs-ui log -n 1 HEAD --pretty=%T
+ DIGEST=dd451b13830662189a1c066a546336a4f775ac72
+ LOCAL_CACHE_DIR=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/tmp/build_cache
+ LOCAL_CACHED_ARTEFACT_PATH=/home/satsha/Documents/leihs.hochschule-rhein-waal.de_hosting/tmp/build_cache/leihs-ui_dd451b13830662189a1c066a546336a4f775ac72.tgz
+ S3_CACHED_ARTEFACT_NAME=leihs-ui_dd451b13830662189a1c066a546336a4f775ac72.tgz
+ BUILD_CACHE_DISABLED=NO
+ set +x
++ dirname ./bin/build-core
+ cd ./bin/..
+ ./bin/deps-install
++ dirname ./bin/deps-install
+ cd ./bin/..
+ cd bootstrap-theme-leihs
+ npm ci --no-audit
./bin/deps-install: line 12: npm: command not found

MSG:

non-zero return code

PLAY RECAP **********************************************************************************************************************************************************************
leihs.hochschule-rhein-waal.de : ok=116  changed=26   unreachable=0    failed=1    skipped=18   rescued=0    ignored=0   
`

**Comment by eins78** [comment]
@satshas The error is about `npm` not being present on your local (or "control") machine. If you are deploying a stable leihs release, only ansible and ruby is actually needed.
* Docs for the build cache: https://github.com/leihs/leihs-instance/blob/master/GUIDE.md#build-cache
* Minimal Docs in case you want to build a custom leihs: https://github.com/leihs/leihs-instance/blob/master/GUIDE.md#build-from-source

Note that you also need to update your inventory:
* leihs 6.1.0 was recently released (and i just updated this template to use it)
* you need to use the latest version of the helper scripts, most importantly this (if you dont want to prepare the cache manually) https://github.com/leihs/leihs-instance/blob/mfa/master/scripts/prepare-build-cache
* upgrade instructions are also in the GUIDE https://github.com/leihs/leihs-instance/blob/master/GUIDE.md#upgrade

**Comment by eins78** [comment]
@satshas meanwhile I've found that curently `npm` is called even when using the prebuilt artefacts. This is a bug that should be fixed in the next version of Leihs. You can either wait for that release or install node.js/npm locally (it wont install packages or compile anything, just needs to be present to not crash).

**Comment by satshas** [comment]
@eins78, I did solve the issue installing npm locally, will anyway wait for the next version to upgrade the current one.

Thanks for your help and work!

Daniele
