### ISSUE TITLE
Wrong server requirements in GUIDE.md

### ISSUE THREAD

**Issue by luniki** [leihs/leihs-instance#26]
https://github.com/leihs/leihs-instance/blob/33f42c9776c9e40d3bd432d83e2ce1d26e328c31/GUIDE.md wants me to install Debian 10 on the server. While deploying v6.9.x to the server it actually wants Debian 11.

**Comment by DrTom** [comment]
This seems to be resolved. 

Please use https://github.com/leihs/leihs/issues in the future.
