### ISSUE TITLE
settings_file_path seems to not be used anywhere

### ISSUE THREAD

**Issue by gojufhv** [leihs/leihs-instance#3]
Maybe I have overlooked it but I cannot find where the settings_file_path in the examples/host_vars_example.yml is used.
If it's not needed anymore I think it would be best to update documentation and examples.

**Comment by eins78** [comment]
@gojufhv It is used in the `leihs-deploy` project, which is a (sub-)submodule of this repo:
https://github.com/leihs/leihs_deploy/blob/33554581199d83a26f5ed6803eec01fc47b776b8/roles/leihs-legacy-install/tasks/settings.yml

**Comment by gojufhv** [comment]
@eins78 thank you for your quick reply
I found my mistake - after git clone of the leihs-instance repo i have to change into the leihs folder and then change to master branch and do a git submodule update :)
