### ISSUE TITLE
Cannot run program "exiftool"

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs-instance#4]
when deploying, making the procure uberjar files when `exiftool` is not installed/not in PATH

**Comment by eins78** [comment]
We should either find out why `exiftool` is called at all and remove that, otherwise mention it in the GUIDE.

**Comment by AnthonyHunt** [comment]
I think this can now be closed? see my comments on the previous issue that I closed.

**Comment by eins78** [comment]
fixed in https://github.com/leihs/leihs_deploy/commit/bbf52b74b41e626ecbcb846f13dcdb10c27679ad
part of leihs 5.2.0 or later
