### ISSUE TITLE
open-vm-tools-dkms in Ubuntu 18.04

### ISSUE THREAD

**Issue by viruz82** [leihs/leihs-instance#6]
The package open-vm-tools-dkms is not available in Ubuntu 18.04 and there is no chance to customize the setup. If I delete the line `- open-vm-tools-dkms` in `leihs/deploy/roles/os-setup/tasks/vmware.yml` It is always overwritten.

`TASK [os-setup : install vmware tools] *******************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to
supply multiple items and specifying `name: {{item}}`, please use `name: [u'open-vm-tools', u'open-vm-tools-dkms']` and remove
the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
failed: [XXX] (item=[u'open-vm-tools', u'open-vm-tools-dkms']) => changed=false
  item:
  - open-vm-tools
  - open-vm-tools-dkms
  msg: No package matching 'open-vm-tools-dkms' is available

PLAY RECAP ***********************************************************************************************************************
XXX : ok=28   changed=4    unreachable=0    failed=1`

**Comment by winampdevil** [comment]
Maybe too late, but her is my solution:

- prepare your deployment

- start first deployment - got the error message above

- now do the following:

delete the line ```- open-vm-tools-dkms``` in ```leihs/deploy/roles/os-setup/tasks/vmware.yml```

comment out the line `git submodule update --recursive --init --force --quiet` in `./scripts/deploy`

- start your second deploy, it should run

**Comment by AnthonyHunt** [comment]
I had the same problem. Didn't think of that!

**Comment by eins78** [comment]
fixed in https://github.com/leihs/leihs_deploy/commit/4fc4e5964c2541e259d019809392d96c92da918d
part of leihs v5.1.1 or later.
