### ISSUE TITLE
Feedback: Docker-based build&deploy (not hosting)

### ISSUE THREAD

**Issue by eins78** [leihs/leihs-instance#7]
The deployment of leihs can now be run inside a Docker container that includes everything needed to build and deploy leihs (Java, node.js, ansible, etc).
As a side effect, that should solve most of the various issues that were reported (but we did not have resources to solve them). It might even work on Windows 😅 (but I have not tried). 

I'll leave this issue open for a while as central place to provide feedback and discuss of there are any problems with this approach. 
If there are still problems with setting up a new instance from scratch (according to the GUIDE.md) they can also be reported here – another upside of using Docker for the build environment is that it's much more reproducible, so problems can be debugged and fixed faster.

---

_Help_

Update `leihs` to 5.2.0:
```bash
cd leihs && git fetch && git checkout 5.2.0 && cd -
```

Update `leihs-instance` using git (if you've forked this repo):

```bash
git remote add upstream https://github.com/leihs/leihs-instance
git pull upstream master
```

Or, update `leihs-instance` without using git:
```bash
curl -L https://github.com/leihs/leihs-instance/archive/master.tar.gz | tar -xzv --strip=1
```

Those are the interesting parts:
* https://github.com/leihs/leihs-instance/blob/master/scripts/deploy-from-docker
* https://github.com/leihs/leihs-instance/blob/master/scripts/-from-docker
* https://github.com/leihs/leihs_deploy/blob/6c74331dbd70b5785856e5f663f719467e8f2e6d/Dockerfile

**Comment by eins78** [comment]
@AnthonyHunt @winampdevil this could be of interest to you 😉

**Comment by eins78** [comment]
also @AnthonyHunt1 🤷‍♂️

**Comment by AnthonyHunt** [comment]
> also @AnthonyHunt1 🤷‍♂️

You've found my secret double identity.... I forgot to switch between work and personal one night... my bad.

**Comment by AnthonyHunt** [comment]
I think the docker approach is going to be amazing! Our IT team have said that unless the install/update process became more fluid they would end support.  Even though I'm the one doing it .... and I'm nothing to do with IT. 🤷‍♂️

I can't try it for a few days as I'm desperately trying to write a script to ingest our AD-LDAP into LEIHS. My programming days are long behind me so I'm having to relearn another language...

**Comment by winampdevil** [comment]
Have tried the docker-based installation routine with ubuntu 18.04.5.  Key-based ssh connection from local shell to remote server is working for any user, also for root.

Deployment of leihs shows the same behavior as described above by AnthonyHunt (https://github.com/leihs/leihs-instance/issues/7#issuecomment-678559068)

System for deployment is a VirtualBox with a clean ubuntu 18.04.4 LTS and docker v19.03.14. Too new?
Ansible is not installed, is this necessary?

Server is also a physical machine, also with ubuntu 18.04.4 LTS

**Comment by tilllt** [comment]
Haven't dealt with Leihs for a really long time, but I asked in 2017 about docker support and basically got a lengthy explanation by the Leihs team why they wouldn't support docker. 

Cool they seem to changing their mind.

 the general idea to use ansible playbooks for a leihs setup was and is a pretty "unusual" decision (to not say bad decision)... It is neither a software that you deploy on a weekly base not is it super complex in terms of dependencies. A well supported purely docker based approach would make leihs much more usable for small institutions and honestly, from my limited insight of deployment techniques, i don't see why software like gitlab or zammad can be setup in 5 minutes while Leihs wants a dedicated server and yadda yadda yadda. If they want to make it easier for admins of huge installations they could add docker installation and Kubernetes helm charts.

**Comment by tilllt** [comment]
Frankly, using ansible in a docker is "shooting sparrows with cannon" or even "von hinten durch die Brust ins Auge" as they say in german.

**Comment by eins78** [comment]
Starting with version 6 all Leihs releases will have prebuilt artefacts published on GitHub (docs: https://github.com/leihs/leihs-instance/blob/943994496d0017a5dea03026dff08efa0b3e3350/GUIDE.md#build-cache).

That means docker-based deploy is now much less important because only Ruby and ansible need to be installed on the local machine. It is still supported for environments when even installing those (globally) is an issue, and to provide a quick way to use the right version of those tool when managing multiple leihs instances.
